Repository fga-eps-mds/2020.2-Projeto-Kokama-Wiki, pull requests merged in 2021-02, with the labels that each got.

#13 Adiciona licença
  LICENSE
Labels: 0-EPS, 1-Documentation

#9 Adiciona templates de issues e pull request do repositório
  .github/ISSUE_TEMPLATE/template-gen-rico-de-issues.md
  .github/ISSUE_TEMPLATE/template-novas-funcionalidades.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 0-EPS, 0-Scrum Master

#14 Cria wiki com MKDocs Material
  .github/workflows/ci.yml
  docker-compose.yml
  docs/assets/img/logo/.placeholder
  docs/index.md
  docs/management/sprint-0.md
  docs/product/visual-identity.md
  docs/project/product-roadmap.md
  mkdocs.yml
Labels: 0-DevOps, 0-EPS, 0-Scrum Master, 1-Documentation

#20 15 landing page
  docs/assets/css/bootstrap.min.css
  docs/assets/css/paper-kit.css
  docs/assets/css/paper-kit.css.map
  docs/assets/css/paper-kit.min.css
  docs/assets/fonts/nucleo-icons.eot
  docs/assets/fonts/nucleo-icons.ttf
  docs/assets/fonts/nucleo-icons.woff
  docs/assets/fonts/nucleo-icons.woff2
  docs/assets/img/apple-icon.png
  docs/assets/img/blurred-image-1.jpg
  docs/assets/img/favicon.ico
  docs/assets/img/favicon.png
  docs/assets/img/floresta.jpg
  docs/assets/img/logo/.placeholder
  docs/assets/js/core/bootstrap.min.js
  docs/assets/js/core/jquery.min.js
  docs/assets/js/core/popper.min.js
  docs/assets/js/paper-kit.js
  docs/assets/js/paper-kit.js.map
  docs/assets/js/paper-kit.min.js
  docs/index.html
  docs/index.md
  mkdocs.yml
Labels: 0-DevOps, 1-Documentation

#24 Adiciona documentação da sprint 0 para a wiki
  docs/assets/img/availability-board.png
  docs/assets/img/sprints/sprint-0/burndown.png
  docs/assets/img/sprints/sprint-0/cumulative-flow.png
  docs/assets/img/sprints/sprint-0/knowledge-board-after.png
  docs/assets/img/sprints/sprint-0/knowledge-board-before.png
  docs/assets/img/sprints/sprint-0/velocity.png
  docs/management/availability-board.md
  docs/management/sprint-0.md
  docs/management/sprints/sprint-0.md
  mkdocs.yml
Labels: 0-EPS, 0-Scrum Master, 1-Documentation

#39 Adiciona documentação do planejamento da Sprint 1
  docs/assets/css/extra.css
  docs/management/sprints/sprint-1-planning.md
  mkdocs.yml
Labels: 0-EPS, 1-Documentation, 1-Meeting

#40 Adiciona revisão e retrospectiva da sprint 1 para a wiki
  docs/assets/img/sprints/sprint-1/burndown.png
  docs/assets/img/sprints/sprint-1/cumulative-flow.png
  docs/assets/img/sprints/sprint-1/knowledge-board-after.png
  docs/assets/img/sprints/sprint-1/knowledge-board-before.png
  docs/assets/img/sprints/sprint-1/knowledge-board-topics.png
  docs/assets/img/sprints/sprint-1/velocity.png
  docs/management/sprints/sprint-1-review-retrospective.md
  mkdocs.yml
Labels: 0-EPS, 0-Scrum Master, 1-Documentation, 1-Meeting

#41 Adiciona plano de comunicação da equipe para a wiki
  docs/management/communication-plan.md
  mkdocs.yml
Labels: 0-Scrum Master, 1-Documentation, 1-Meeting

#43 33 rich picture
  docs/assets/img/rich-picture/righ-picture.png
  docs/project/rich-picture.md
  mkdocs.yml
Labels: 0-MDS, 1-Documentation

#45 Documentar reunião com PO
  docs/management/po-meetings/meeting-1.md
  mkdocs.yml
Labels: 0-EPS, 0-MDS, 0-Product Owner, 1-Documentation

#38 37 documentar prototipo [baixa fidelidade e media]
  docs/assets/img/prototype/low/prototype_1_1.png
  docs/assets/img/prototype/low/prototype_1_2.png
  docs/assets/img/prototype/low/prototype_1_3.png
  docs/assets/img/prototype/low/prototype_2_1.png
  docs/assets/img/prototype/low/prototype_2_2.png
  docs/assets/img/prototype/low/prototype_3_1.jpg
  docs/assets/img/prototype/low/prototype_3_2.jpg
  docs/assets/img/prototype/low/prototype_4_1.png
  docs/assets/img/prototype/mid/prototype_1_1.png
  docs/assets/img/prototype/mid/prototype_1_2.png
  docs/index.html
  docs/project/high-prototype.md
  docs/project/low-prototype.md
  docs/project/mid-prototype.md
  docs/project/visual-identity.md
  mkdocs.yml
Labels: 0-EPS, 1-Documentation, 1-Meeting

#44 34 documento visao
  docs/project/vision-document.md
  mkdocs.yml
Labels: 0-MDS, 1-Documentation, 1-Meeting

#47 [WIP] Adiciona artefatos da Lean Inception para a wiki
  docs/assets/img/lean-inception/canvas-mvp-1.png
  docs/assets/img/lean-inception/canvas-mvp-2.png
  docs/assets/img/lean-inception/canvas-mvp.png
  docs/assets/img/lean-inception/functionalities.png
  docs/assets/img/lean-inception/functionalities_review.png
  docs/assets/img/lean-inception/is-is-not-does-does-not.png
  docs/assets/img/lean-inception/journey-1.png
  docs/assets/img/lean-inception/journey-2.png
  docs/assets/img/lean-inception/journey-3.png
  docs/assets/img/lean-inception/persona-1.png
  docs/assets/img/lean-inception/persona-2.png
  docs/assets/img/lean-inception/persona-3.png
  docs/assets/img/lean-inception/product-goals.png
  docs/assets/img/lean-inception/product-vision-1.png
  docs/assets/img/lean-inception/product-vision-2.png
  docs/assets/img/lean-inception/product-vision-3.png
  docs/assets/img/lean-inception/product-vision.png
  docs/assets/img/lean-inception/sequencer.png
  docs/assets/img/lean-inception/team.png
  docs/project/lean-inception/brainstorm.md
  docs/project/lean-inception/canvas-mvp.md
  docs/project/lean-inception/functionalities-review.md
  docs/project/lean-inception/introduction.md
  docs/project/lean-inception/is-is-not-does-does-not.md
  docs/project/lean-inception/personas.md
  docs/project/lean-inception/product-goals.md
  docs/project/lean-inception/product-vision.md
  docs/project/lean-inception/sequencer.md
  docs/project/lean-inception/user-journey.md
  mkdocs.yml
Labels: 0-EPS, 0-MDS, 0-Scrum Master, 1-Documentation, 1-Meeting
