Repository fga-eps-mds/2020.2-Projeto-Kokama-Wiki, pull requests merged in 2021-03, with the labels that each got.

#46 Roadmap dos papeis
  docs/assets/img/roadmap-papel.png
  docs/management/role-roadmap.md
  mkdocs.yml
Labels: 0-EPS, 1-Documentation

#61 Atualiza links da Lean Inception
  docs/assets/img/lean-inception/canvas-mvp-1.png
  docs/assets/img/lean-inception/canvas-mvp-2.png
  docs/assets/img/lean-inception/canvas-mvp.png
  docs/assets/img/lean-inception/functionalities.png
  docs/assets/img/lean-inception/functionalities_review.png
  docs/assets/img/lean-inception/is-is-not-does-does-not.png
  docs/assets/img/lean-inception/journey-1.png
  docs/assets/img/lean-inception/journey-2.png
  docs/assets/img/lean-inception/journey-3.png
  docs/assets/img/lean-inception/persona-1.png
  docs/assets/img/lean-inception/persona-2.png
  docs/assets/img/lean-inception/persona-3.png
  docs/assets/img/lean-inception/product-goals.png
  docs/assets/img/lean-inception/product-vision-1.png
  docs/assets/img/lean-inception/product-vision-2.png
  docs/assets/img/lean-inception/product-vision-3.png
  docs/assets/img/lean-inception/product-vision.png
  docs/assets/img/lean-inception/sequencer.png
  docs/project/lean-inception/brainstorm.md
  docs/project/lean-inception/canvas-mvp.md
  docs/project/lean-inception/functionalities-review.md
  docs/project/lean-inception/introduction.md
  docs/project/lean-inception/is-is-not-does-does-not.md
  docs/project/lean-inception/personas.md
  docs/project/lean-inception/product-goals.md
  docs/project/lean-inception/product-vision.md
  docs/project/lean-inception/sequencer.md
  docs/project/lean-inception/user-journey.md
Labels: 0-EPS, 0-MDS, 1-Documentation, 1-Meeting

#62 Adiciona revisão e retrospectiva da sprint 2 para a wiki
  docs/assets/img/sprints/sprint-2/burndown.png
  docs/assets/img/sprints/sprint-2/cumulative-flow.png
  docs/assets/img/sprints/sprint-2/knowledge-board-after.png
  docs/assets/img/sprints/sprint-2/knowledge-board-before.png
  docs/assets/img/sprints/sprint-2/knowledge-board-topics.png
  docs/assets/img/sprints/sprint-2/time-eps-mds.png
  docs/assets/img/sprints/sprint-2/time-team.png
  docs/assets/img/sprints/sprint-2/velocity.png
  docs/management/sprints/sprint-2-review-retrospective.md
  mkdocs.yml
Labels: 0-EPS, 0-Scrum Master, 1-Documentation

#66 Adiciona documentação da 2° reunião com a PO
  docs/management/po-meetings/meeting-2.md
  mkdocs.yml
Labels: 0-EPS, 0-Product Owner, 1-Meeting

#59 Adiciona documentação do planejamento da Sprint 2
  docs/management/sprints/sprint-2-planning.md
  mkdocs.yml
Labels: 0-EPS, 0-Scrum Master, 1-Documentation

#65 Adiciona documentação do planejamento da Sprint 3
  docs/management/sprints/sprint-3-planning.md
  mkdocs.yml
Labels: 0-EPS, 0-Scrum Master, 1-Documentation

#63 48 backlog document
  docs/assets/img/product-backlog/product-backlog.png
  docs/project/product-backlog.md
  mkdocs.yml
Labels: 0-EPS, 0-MDS, 1-Documentation, 1-Meeting

#42 36 Visual Identity
  docs/assets/img/visual-identity/logo.png
  docs/assets/img/visual-identity/pallete.png
  docs/assets/img/visual-identity/pallete_example.png
  docs/project/visual-identity.md
Labels: 0-MDS, 0-Product Owner, 1-Documentation, 1-Meeting

#68 Adiciona documentação do teste de usabilidade
  docs/project/usability-test.md
  mkdocs.yml
Labels: 0-EPS, 1-Documentation, 1-Meeting

#70 Added high prototype doc
  docs/assets/img/prototype/high/prototype_1_1.png
  docs/assets/img/prototype/high/prototype_1_2.png
  docs/assets/img/prototype/high/prototype_1_3.png
  docs/assets/img/prototype/high/prototype_1_4.png
  docs/assets/img/prototype/high/prototype_1_5.png
  docs/assets/img/prototype/high/prototype_1_6.png
  docs/assets/img/prototype/high/prototype_1_7.png
  docs/assets/img/prototype/high/prototype_1_8.png
  docs/assets/img/prototype/high/prototype_1_9.png
  docs/project/high-prototype.md
Labels: 0-EPS, 0-Product Owner, 1-Documentation, 1-Meeting

#71 50 visual identity on wiki
  README.md
  docs/assets/css/extra.css
  docs/assets/img/apple-icon.png
  docs/assets/img/blurred-image-1.jpg
  docs/assets/img/favicon.ico
  docs/assets/img/favicon.png
  docs/assets/img/logo.png
  docs/index.html
  mkdocs.yml
Labels: 0-MDS, 1-Documentation

#85 changed repo links
  docs/index.html
  mkdocs.yml
Labels: 0-EPS, 1-Documentation

#89 Adiciona planejamento da sprint 4 para a wiki
  docs/management/sprints/sprint-4-planning.md
  mkdocs.yml
Labels: 0-EPS, 0-Scrum Master, 1-Documentation

#90 Adiciona revisão e retrospectiva da sprint 3 para a wiki
  docs/assets/img/sprints/sprint-3/burndown.png
  docs/assets/img/sprints/sprint-3/cumulative-flow.png
  docs/assets/img/sprints/sprint-3/knowledge-board-after.png
  docs/assets/img/sprints/sprint-3/knowledge-board-before.png
  docs/assets/img/sprints/sprint-3/knowledge-board-topics.png
  docs/assets/img/sprints/sprint-3/time-eps-mds.png
  docs/assets/img/sprints/sprint-3/time-team.png
  docs/assets/img/sprints/sprint-3/velocity.png
  docs/management/sprints/sprint-1-review-retrospective.md
  docs/management/sprints/sprint-2-review-retrospective.md
  docs/management/sprints/sprint-3-planning.md
  docs/management/sprints/sprint-3-review-retrospective.md
  mkdocs.yml
Labels: 0-EPS, 0-Scrum Master, 1-Documentation, 1-Meeting

#88 81 - Automatização de relatórios com script
  .vscode/history.code-snippets
  .vscode/team.code-snippets
  scripts/issues_crawler.js
  scripts/planning_generator.py
Labels: 0-EPS, 0-Scrum Master, 1-Documentation

#86 79 evm
  docs/management/evm.md
  mkdocs.yml
Labels: 0-EPS, 0-Product Owner, 1-Documentation

#100 78 - Roadmap do produto
  docs/assets/img/product-backlog/product-backlog.png
  docs/management/product-roadmap.md
  docs/project/product-backlog.md
  docs/project/product-roadmap.md
  mkdocs.yml
Labels: 0-EPS, 0-Scrum Master, 1-Documentation

#67 48 Product Backlog
  docs/project/product-backlog.md
  docs/project/rich-picture.md
Labels: 0-EPS, 0-MDS, 1-Documentation, 2-Meeting

#113 Adiciona revisão e retrospectiva da sprint 4 para a wiki
  docs/assets/img/sprints/sprint-4/burndown.png
  docs/assets/img/sprints/sprint-4/knowledge-board-after.png
  docs/assets/img/sprints/sprint-4/knowledge-board-before.png
  docs/assets/img/sprints/sprint-4/knowledge-board-topics-compare.png
  docs/assets/img/sprints/sprint-4/time-eps-mds.png
  docs/assets/img/sprints/sprint-4/time-team.png
  docs/assets/img/sprints/sprint-4/velocity.png
  docs/management/sprints/sprint-4-review-retrospective.md
  mkdocs.yml
Labels: 0-EPS, 0-Scrum Master, 1-Documentation

#114 Adiciona planejamento da sprint 5 para a wiki
  docs/management/sprints/sprint-5-planning.md
  mkdocs.yml
Labels: 0-EPS, 0-Scrum Master, 1-Documentation

#116 Adiciona planejamento da sprint 6 para a wiki
  docs/management/sprints/sprint-6-planning.md
  mkdocs.yml
Labels: 0-EPS, 0-Scrum Master, 1-Documentation, 2-Meeting

#64 55 Documento de Arquitetura
  docs/assets/img/architecture/api_package_diagram.png
  docs/assets/img/architecture/architecture_diagram.png
  docs/assets/img/architecture/front_end_package_diagram.png
  docs/assets/img/architecture/logic_diagram.png
  docs/project/architecture-document.md
  mkdocs.yml
Labels: 0-EPS, 0-MDS, 1-Backend, 1-Documentation, 2-Meeting

#118 Update logo
  docs/assets/img/logo.png
Labels: 0-MDS, 1-Documentation

#119 117 Adiciona plano metodológico da equipe
  docs/assets/img/pipeline/kanban-pipeline.png
  docs/management/methodology-plan.md
  mkdocs.yml
Labels: 0-EPS, 0-Scrum Master, 1-Documentation, 2-Meeting

#120 107 Revisão de Projeto
  .github/PULL_REQUEST_TEMPLATE.md
  docs/management/sprints/sprint-1-review-retrospective.md
  docs/management/sprints/sprint-3-review-retrospective.md
  docs/project/vision-document.md
  mkdocs.yml
Labels: 0-EPS, 1-Documentation

#121 Adiciona vídeo da release 1 na wiki
  docs/assets/css/extra.css
  docs/releases/release-1.md
  mkdocs.yml
Labels: 0-EPS, 0-MDS, 1-Documentation, 2-Meeting
